# Generated by Django 3.1.4 on 2020-12-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('publish_date', models.DateTimeField()),
                ('heading0', models.CharField(default='', max_length=500)),
                ('heading1', models.CharField(default='', max_length=500)),
                ('sub_heading', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
