# Generated by Django 3.1.4 on 2020-12-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201217_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Con_heading0',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Con_heading1',
            field=models.TextField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Con_sub_heading',
            field=models.TextField(default='', max_length=30000),
        ),
    ]
