# Generated by Django 3.1.1 on 2020-11-24 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201124_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address2',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 24, 15, 58, 46, 393660)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone_no',
            field=models.IntegerField(default='', max_length=15),
        ),
    ]
