# Generated by Django 3.1.1 on 2020-12-03 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201203_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 13, 58, 56, 567441)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone_no',
            field=models.CharField(default='', max_length=15),
        ),
    ]
