# Generated by Django 3.1.4 on 2020-12-17 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201217_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 17, 13, 49, 33, 339776)),
        ),
    ]
